language: python
matrix:
  include:
  - env: BUILD_NAME=UNIT
    python: '2.7'
  - env: BUILD_NAME=UNIT
    python: '3.3'
  - env: BUILD_NAME=UNIT
    python: '3.4'
  - env: BUILD_NAME=UNIT
    python: '3.5'

  - env: BUILD_NAME=LINT
    python: '2.7'
  - env: BUILD_NAME=LINT
    python: '3.5'

  - env: BUILD_NAME=DOCS
    python: '2.7'
  - env: BUILD_NAME=DOCS
    python: '3.5'

  # Python 2.7 with ghdl mcode
  - env: BUILD_NAME=ACCEPTANCE
    python: '2.7'
    os: linux
    sudo: false
    addons:
      apt:
        packages:
        - gnat
    before_script:
    - git clone --depth 1 https://github.com/tgingold/ghdl.git ghdl
    - cd ghdl
    - mkdir build-mcode
    - cd build-mcode
    - ../configure --prefix=../../install-ghdl-mcode/
    - make
    - make install
    - cd ../../
    - export PATH=$PATH:install-ghdl-mcode/bin/
    - export VUNIT_SIMULATOR=ghdl

  # Python 3.5 with ghdl llvm
  - env: BUILD_NAME=ACCEPTANCE
    python: '3.5'
    os: linux
    sudo: required
    dist: trusty
    before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y gnat-4.8 zlib1g-dev
    - sudo apt-get install -y llvm-3.5-dev llvm-3.5-tools libedit-dev
    before_script:
    - git clone --depth 1 https://github.com/tgingold/ghdl.git ghdl
    - cd ghdl
    - mkdir build-llvm
    - cd build-llvm
    - ../configure --prefix=../../install-ghdl-llvm/ --with-llvm-config=llvm-config-3.5
    - make
    - make install
    - cd ../../
    - export PATH=$PATH:install-ghdl-llvm/bin/
    - export VUNIT_SIMULATOR=ghdl

install:
- pip install tox

script:
- python travis.py ${BUILD_NAME}
