language: python
python: '3.8'
install: pip install tox
script:
  - git fetch --unshallow --tags
  - python tools/release.py validate
# Deploy to PyPI whenever the package version has changed
# When a package version has not changed a new upload will not be triggered
if: tag IS present
deploy:
  provider: pypi
  distributions: sdist
  skip_cleanup: true
  skip_upload_docs: true
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  on:
    repo: VUnit/vunit
    all_branches: true
